

// function bubblesort(array) {

//     let swapped
//     do {
//         swapped = false

         
//     for(let i = 0; i<array.length-1;i++){

//         if (array[i]>array[i+1]) {
//             let temp=array[i]
//             array[i]=array[i+1]
//             array[i+1]=temp
//             swapped=true
//         }
//     }

//     } while (swapped);
   
   
// }

// const array=[6,3,-1,78,-7,5]

// bubblesort(array)
// console.log(array);


// function bubbleSort(array){

//     let swapped 
//     do {
//         swapped = false

//         for (let i = 0; i < array.length; i++) {
        
//             if (array[i]>array[i+1]) {
//                 let temp = array[i]
//                 array[i]=array[i+1]
//                 array[i+1]=temp
//                 swapped=true
                
//             }
            
//         }
        
//     } while (swapped);

   
// }


// const array= [1,2,3,4,-5,39]


// bubbleSort(array)
// console.log(array);




// function bubblesort(array) {
//     let swapped

//     do {
//         swapped = false

//         for (let i = 0; i < array.length; i++) {

//             if (array[i]>array[i+1]) {
                
//                 let temp = array[i]
//                 array[i]=array[i+1]
//                 array[i+1]= temp
//                 swapped = true
//             }
//         }          
//     } while (swapped);    
// }
// const array = [ 1,2,3,4,5,-6,-7]

// bubblesort(array)
// console.log(array)







// function bubblesort(array) {

//     let swapped

//     do {
//         swapped= false
//         for (let i = 0; i < array.length; i++) {
       
//             if (array[i]>array[i+1]) {
                
//                 let temp = array[i]
//                 array[i]=array[i+1]
//                 array[i+1]=temp
//                 swapped= true
//             }
            
//         }
    
//     } while (swapped);
//   return array
// }


// console.log(bubblesort([1,2,3,-4,5,6,7,-90]));




// function bubbleSort( array){

//     let swapped = true

//     do {
//           swapped= false


//         for (let i = 0; i < array.length; i++) {
//             if (array[i]>array[i+1]) {
               
//                let temp = array[i]
//                array[i]=array[i+1]
//                array[i+1]= temp
//                swapped= true

//             }
           
//        }
        
//     } while (swapped);
//    return array
// }

// console.log(bubbleSort([98,8,3,5,6,7,1,1,]));


// function bubblesort(array) {
//    let swapped
//    do {
//       swapped = false
//       for (let i = 0; i < array.length; i++) {
//          if (array[i]>array[i+1]) {
//           let temp = array[i]
//           array[i]= array[i+1]
//           array[i+1]= temp
//           swapped = true
//          }
//     }
//    } while (swapped);
//    return array
// }

//  console.log( bubblesort([9,8,7,6,5,4,3,2,1,-88]));


// function bubblesort(array) {
//    let swapped
//    do {
//       swapped = false
//       for (let i = 0; i < array.length; i++) {
//          if (array[i]>array[i+1]) {
//            let temp = array[i]
//            array[i]= array[i+1]
//            array[i+1]= temp
//            swapped = true
//          } 
//      } 
//    } while (swapped);
//    return array
// }

// console.log(bubblesort([9,8,7,6,5,4,3,2,1,0]));





// function bubblesort(array) {
//    let swapped

//    do {
//       swapped= false

//       for (let i = 0; i < array.length; i++) {
//          if (array[i+1]<array[i]) {
//             let temp = array[i]
//             array[i]=array[i+1]
//             array[i+1]= temp
//             swapped = true
//          }
      
//    }
      
//    } while (swapped);
//    return array
  
// }
// console.log(bubblesort([9,8,7,6,5,4,3,2,1]));


// function bubbleSort(array) {
// let swapped
// do {
// swapped = false
//    for (let i = 0; i < array.length; i++) {
//       if (array[i+1]<array[i]) {
//         let temp = array[i]
//         array[i]= array[i+1]
//         array[i+1]= temp
//         swapped = true
//       }
//   }
// } while (swapped);
//    return array 
// }

// console.log(bubbleSort([9,8,7,6,5,4]));




// function bubblesort(array) {
//    let swapped
//    do {
//          swapped=false
//       for (let i = 0; i < array.length; i++) {
       
//          if (array[i+1]<array[i]) {
//             let temp = array[i]
//             array[i]= array[i+1]
//             array[i+1]= temp
//             swapped=true
//          }  
//       }
//    } while (swapped);
//   return array
// }
// console.log(bubblesort([9,8,7,6,5,4]));

// function bubblesort(array) {
//    let swapped
//    do {
//       swapped = false
//       for (let i = 0; i < array.length; i++) {   
//          if (array[i+1]<array[i]) {
//             let temp = array[i]
//             array[i]= array[i+1]
//             array[i+1]= temp
//             swapped=true
//          }
//       }
//    } while (swapped);
//    return array
// }
// console.log(bubblesort([9,8,3,2,1,99,-1,-5]));


// function bubblesort(array) {
   
//    let swapped
//    do {
      
//       swapped = false
      
//       for (let i = 0; i < array.length; i++) {
//            if (array[i+1]<array[i]) {
//             let temp = array[i]
//             array[i]= array[i+1]
//             array[i+1]= temp

//             swapped = true
//            }
         
//       }
//    } while (swapped);
//    return array
// }

// console.log(bubblesort([8,7,6,5,4,319,0,2,3,5]));


function bubblesort(array) {
   let swapped 
   do {
      swapped= false
      for (let i = 0; i < array.length; i++) {   
         if (array[i+1]<array[i]) {
            let temp = array[i]
            array[i] = array[i+1]
            array[i+1]=temp 
            swapped = true
         }      
      }
   } while (swapped);
  return array
}
console.log(bubblesort([9,8,7,6,5,4,3,2,1]));